name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository .."
        uses: actions/checkout@v4.2.2
      - name: "Setup Nodes .."
        uses: actions/setup-node@v4
        with:
          node-version: package.json
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository .."
        uses: actions/checkout@v4.2.2
      - name: "Setup Nodes .."
        uses: actions/setup-node@v4
        with:
          node-version: package.json
      - name: "Install Dependencies .."
        run: npm ci
      - name: "Publish Package .."
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
